// ─── Madhab Bakery · Product Catalog ────────────────────────────────────────
// Images use Unsplash free-to-use URLs
const UNSPLASH = (id, w = 600, h = 400) =>
  `https://source.unsplash.com/${id}/${w}x${h}`;

export const CATEGORIES = [
  { id: 'cakes',     label: 'Cakes',     emoji: '🎂', color: 'bg-rose-100',   textColor: 'text-rose-700',   count: 24 },
  { id: 'breads',    label: 'Breads',    emoji: '🍞', color: 'bg-amber-100',  textColor: 'text-amber-800',  count: 18 },
  { id: 'pastries',  label: 'Pastries',  emoji: '🥐', color: 'bg-orange-100', textColor: 'text-orange-800', count: 14 },
  { id: 'cookies',   label: 'Cookies',   emoji: '🍪', color: 'bg-yellow-100', textColor: 'text-yellow-800', count: 20 },
  { id: 'muffins',   label: 'Muffins',   emoji: '🧁', color: 'bg-pink-100',   textColor: 'text-pink-700',   count: 12 },
  { id: 'cupcakes',  label: 'Cupcakes',  emoji: '🧁', color: 'bg-purple-100', textColor: 'text-purple-700', count: 16 },
  { id: 'donuts',    label: 'Donuts',    emoji: '🍩', color: 'bg-red-100',    textColor: 'text-red-700',    count: 10 },
  { id: 'brownies',  label: 'Brownies',  emoji: '🍫', color: 'bg-stone-100',  textColor: 'text-stone-700',  count: 8  },
];

export const PRODUCTS = [
  // ── CAKES ──────────────────────────────────────────────────────────────────
  {
    id: 'p001',
    name: 'Belgian Chocolate Truffle Cake',
    slug: 'belgian-chocolate-truffle-cake',
    category: 'cakes',
    price: 849,
    originalPrice: 999,
    rating: 4.8,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop',
    ],
    weight: '500g',
    serves: '4-6',
    description: 'Rich and indulgent Belgian chocolate truffle cake with layers of dark chocolate ganache, Swiss meringue buttercream, and a glossy chocolate mirror glaze.',
    ingredients: ['Belgian dark chocolate', 'eggs', 'butter', 'cream', 'sugar', 'flour'],
    tags: ['bestseller', 'featured', 'chocolate'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Dark Chocolate', 'Milk Chocolate', 'White Chocolate'],
    sizes: ['500g', '1kg', '2kg'],
  },
  {
    id: 'p002',
    name: 'Mango Passion Fruit Cake',
    slug: 'mango-passion-fruit-cake',
    category: 'cakes',
    price: 749,
    originalPrice: 899,
    rating: 4.7,
    reviewCount: 218,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop'],
    weight: '500g',
    serves: '4-6',
    description: 'Light and airy sponge cake layered with fresh mango cream and passion fruit curd. The ultimate tropical delight.',
    ingredients: ['alphonso mango', 'passion fruit', 'eggs', 'whipped cream', 'sugar', 'flour'],
    tags: ['seasonal', 'featured'],
    isNew: true,
    isBestSeller: false,
    inStock: true,
    badge: 'New',
    flavours: ['Mango', 'Mango Passion'],
    sizes: ['500g', '1kg'],
  },
  {
    id: 'p003',
    name: 'Red Velvet Celebration Cake',
    slug: 'red-velvet-celebration-cake',
    category: 'cakes',
    price: 799,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 512,
    image: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=600&h=400&fit=crop'],
    weight: '500g',
    serves: '6-8',
    description: 'Classic red velvet cake with a velvety crumb, tangy cream cheese frosting, and delicate red crumble topping.',
    ingredients: ['cocoa', 'red gel colour', 'cream cheese', 'butter', 'eggs', 'buttermilk'],
    tags: ['bestseller', 'featured', 'celebration'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Classic'],
    sizes: ['500g', '1kg', '2kg'],
  },
  {
    id: 'p004',
    name: 'Strawberry Shortcake',
    slug: 'strawberry-shortcake',
    category: 'cakes',
    price: 599,
    originalPrice: 699,
    rating: 4.6,
    reviewCount: 185,
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&h=400&fit=crop'],
    weight: '400g',
    serves: '3-4',
    description: 'Light genoise sponge sandwiched with fresh strawberries and whipped cream. A timeless summer classic.',
    ingredients: ['fresh strawberries', 'whipping cream', 'genoise sponge', 'vanilla'],
    tags: ['seasonal'],
    isNew: false,
    isBestSeller: false,
    inStock: true,
    badge: 'Sale',
    flavours: ['Strawberry', 'Mixed Berry'],
    sizes: ['400g', '800g'],
  },

  // ── BREADS ─────────────────────────────────────────────────────────────────
  {
    id: 'p005',
    name: 'Classic Sourdough Boule',
    slug: 'classic-sourdough-boule',
    category: 'breads',
    price: 249,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 621,
    image: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=600&h=400&fit=crop'],
    weight: '800g',
    serves: '6-8',
    description: 'Hand-crafted sourdough with a caramelised crust and chewy open crumb. Made with our 5-year-old starter and slow 48-hour fermentation.',
    ingredients: ['bread flour', 'water', 'sourdough starter', 'salt'],
    tags: ['bestseller', 'vegan'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Plain', 'Seeded', 'Olive & Rosemary'],
    sizes: ['400g', '800g'],
  },
  {
    id: 'p006',
    name: 'Multigrain Sandwich Loaf',
    slug: 'multigrain-sandwich-loaf',
    category: 'breads',
    price: 189,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 390,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop'],
    weight: '700g',
    serves: '10-12 slices',
    description: 'Wholesome loaf with whole wheat, oats, flaxseeds and sunflower seeds. Perfect for healthy everyday sandwiches.',
    ingredients: ['whole wheat flour', 'oats', 'flaxseeds', 'sunflower seeds', 'honey', 'yeast'],
    tags: ['healthy', 'whole grain'],
    isNew: false,
    isBestSeller: false,
    inStock: true,
    badge: null,
    flavours: ['Classic Multigrain'],
    sizes: ['350g', '700g'],
  },
  {
    id: 'p007',
    name: 'Garlic & Herb Focaccia',
    slug: 'garlic-herb-focaccia',
    category: 'breads',
    price: 219,
    originalPrice: 249,
    rating: 4.8,
    reviewCount: 277,
    image: 'https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=600&h=400&fit=crop'],
    weight: '450g',
    serves: '4-6',
    description: 'Pillowy Italian flatbread drizzled with extra virgin olive oil, roasted garlic, fresh rosemary and sea salt flakes.',
    ingredients: ['all-purpose flour', 'olive oil', 'garlic', 'rosemary', 'sea salt', 'yeast'],
    tags: ['italian', 'vegan'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Sale',
    flavours: ['Garlic Herb', 'Tomato Olive', 'Onion Thyme'],
    sizes: ['450g'],
  },

  // ── PASTRIES ───────────────────────────────────────────────────────────────
  {
    id: 'p008',
    name: 'Butter Croissants (Pack of 4)',
    slug: 'butter-croissants-pack-4',
    category: 'pastries',
    price: 299,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 834,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&h=400&fit=crop'],
    weight: '200g',
    serves: '4',
    description: 'Flaky, buttery croissants made with pure European-style butter through a traditional 3-day lamination process. Shatters perfectly on bite.',
    ingredients: ['all-purpose flour', 'European butter', 'milk', 'yeast', 'sugar', 'salt'],
    tags: ['bestseller', 'featured', 'french'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Plain', 'Almond', 'Chocolate', 'Ham & Cheese'],
    sizes: ['Pack of 2', 'Pack of 4', 'Pack of 6'],
  },
  {
    id: 'p009',
    name: 'Cinnamon Danish Swirls',
    slug: 'cinnamon-danish-swirls',
    category: 'pastries',
    price: 249,
    originalPrice: 299,
    rating: 4.7,
    reviewCount: 198,
    image: 'https://images.unsplash.com/photo-1558401391-07c38b2843d4?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1558401391-07c38b2843d4?w=600&h=400&fit=crop'],
    weight: '240g',
    serves: '4',
    description: 'Tender danish pastry swirled with warming cinnamon-sugar filling, topped with cream cheese glaze and toasted pecans.',
    ingredients: ['danish dough', 'cinnamon', 'brown sugar', 'cream cheese', 'pecans'],
    tags: ['featured'],
    isNew: true,
    isBestSeller: false,
    inStock: true,
    badge: 'New',
    flavours: ['Cinnamon', 'Cardamom Rose'],
    sizes: ['Pack of 4'],
  },

  // ── COOKIES ────────────────────────────────────────────────────────────────
  {
    id: 'p010',
    name: 'New York Chocolate Chip Cookies',
    slug: 'ny-chocolate-chip-cookies',
    category: 'cookies',
    price: 199,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 567,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=400&fit=crop'],
    weight: '300g',
    serves: '10–12',
    description: 'Thick, chewy cookies with crispy edges and gooey centers loaded with two types of chocolate chips. Browned butter gives them a nutty depth.',
    ingredients: ['browned butter', '70% dark chocolate chips', 'milk chocolate chips', 'bread flour', 'eggs', 'brown sugar'],
    tags: ['bestseller', 'featured'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Double Chocolate', 'White Chocolate Macadamia', 'Peanut Butter'],
    sizes: ['150g (6 pcs)', '300g (12 pcs)', '600g (24 pcs)'],
  },
  {
    id: 'p011',
    name: 'Pistachio Rose Shortbread',
    slug: 'pistachio-rose-shortbread',
    category: 'cookies',
    price: 249,
    originalPrice: 279,
    rating: 4.6,
    reviewCount: 134,
    image: 'https://images.unsplash.com/photo-1618426703623-150fd9e4b438?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1618426703623-150fd9e4b438?w=600&h=400&fit=crop'],
    weight: '200g',
    serves: '8–10',
    description: 'Elegant melt-in-mouth butter shortbread with crushed pistachios and rose water, finished with a dusting of icing sugar.',
    ingredients: ['butter', 'icing sugar', 'flour', 'pistachios', 'rosewater', 'cardamom'],
    tags: ['premium', 'gifting'],
    isNew: true,
    isBestSeller: false,
    inStock: true,
    badge: 'New',
    flavours: ['Pistachio Rose', 'Lavender Lemon'],
    sizes: ['200g', '400g'],
  },

  // ── MUFFINS ────────────────────────────────────────────────────────────────
  {
    id: 'p012',
    name: 'Blueberry Lemon Muffins (Pack of 6)',
    slug: 'blueberry-lemon-muffins',
    category: 'muffins',
    price: 279,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 312,
    image: 'https://images.unsplash.com/photo-1558303695-3e926c2e0f11?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1558303695-3e926c2e0f11?w=600&h=400&fit=crop'],
    weight: '360g',
    serves: '6',
    description: 'Moist and fluffy muffins bursting with fresh blueberries and bright lemon zest, crowned with a crunchy sugar-lemon streusel top.',
    ingredients: ['blueberries', 'lemon zest', 'buttermilk', 'flour', 'sugar', 'eggs'],
    tags: ['bestseller', 'featured'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Blueberry Lemon', 'Double Chocolate', 'Banana Walnut', 'Bran & Raisin'],
    sizes: ['Pack of 6'],
  },

  // ── CUPCAKES ───────────────────────────────────────────────────────────────
  {
    id: 'p013',
    name: 'Classic Vanilla Bean Cupcakes (Box of 6)',
    slug: 'vanilla-bean-cupcakes-6',
    category: 'cupcakes',
    price: 329,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 423,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&h=400&fit=crop'],
    weight: '480g',
    serves: '6',
    description: 'Fluffy vanilla sponge cupcakes topped with swirls of Swiss meringue buttercream made with real vanilla bean paste.',
    ingredients: ['vanilla bean', 'butter', 'eggs', 'flour', 'Swiss meringue'],
    tags: ['featured', 'celebration'],
    isNew: false,
    isBestSeller: false,
    inStock: true,
    badge: null,
    flavours: ['Vanilla', 'Strawberry', 'Salted Caramel', 'Lemon Meringue'],
    sizes: ['Box of 6', 'Box of 12'],
  },

  // ── DONUTS ─────────────────────────────────────────────────────────────────
  {
    id: 'p014',
    name: 'Glazed Donuts Assortment (Box of 6)',
    slug: 'glazed-donuts-assortment',
    category: 'donuts',
    price: 349,
    originalPrice: 399,
    rating: 4.6,
    reviewCount: 256,
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&h=400&fit=crop'],
    weight: '540g',
    serves: '6',
    description: 'Pillowy yeast donuts with a feather-light crumb in a mix of flavours: classic glaze, chocolate, strawberry, and more.',
    ingredients: ['flour', 'butter', 'eggs', 'milk', 'yeast', 'assorted glazes'],
    tags: ['featured', 'fun'],
    isNew: false,
    isBestSeller: false,
    inStock: true,
    badge: 'Sale',
    flavours: ['Mixed Box', 'All Chocolate', 'All Glaze'],
    sizes: ['Box of 6', 'Box of 12'],
  },

  // ── BROWNIES ───────────────────────────────────────────────────────────────
  {
    id: 'p015',
    name: 'Fudgy Espresso Brownies (Pack of 4)',
    slug: 'fudgy-espresso-brownies',
    category: 'brownies',
    price: 299,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 445,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=400&fit=crop'],
    weight: '400g',
    serves: '4',
    description: 'Ultra-fudgy, dense brownies with a shiny crinkle top, laced with espresso to amplify the rich dark chocolate flavour.',
    ingredients: ['70% dark chocolate', 'espresso', 'butter', 'eggs', 'flour', 'cocoa powder'],
    tags: ['bestseller', 'featured', 'chocolate'],
    isNew: false,
    isBestSeller: true,
    inStock: true,
    badge: 'Best Seller',
    flavours: ['Espresso', 'Salted Caramel', 'Walnut', 'Nutella Swirl'],
    sizes: ['Pack of 4', 'Pack of 8'],
  },
  {
    id: 'p016',
    name: 'Caramel Walnut Tart',
    slug: 'caramel-walnut-tart',
    category: 'pastries',
    price: 449,
    originalPrice: 499,
    rating: 4.7,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1519915928517-0c1f6e97d1a5?w=600&h=400&fit=crop',
    images: ['https://images.unsplash.com/photo-1519915928517-0c1f6e97d1a5?w=600&h=400&fit=crop'],
    weight: '350g',
    serves: '4-6',
    description: 'Buttery shortcrust pastry shell filled with a silky salted caramel custard and topped with candied walnuts.',
    ingredients: ['shortcrust pastry', 'caramel', 'walnuts', 'cream', 'eggs', 'sea salt'],
    tags: ['premium'],
    isNew: false,
    isBestSeller: false,
    inStock: true,
    badge: 'Sale',
    flavours: ['Caramel Walnut', 'Lemon Curd', 'Chocolate Hazelnut'],
    sizes: ['350g', '700g'],
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Aarav Mehta',
    location: 'Mumbai',
    rating: 5,
    avatar: 'AM',
    text: 'Ordered the Belgian Chocolate Truffle Cake for my wife\'s birthday — everyone was speechless! Rich, moist, absolutely divine. Will definitely order again.',
    date: '2 weeks ago',
    product: 'Belgian Chocolate Truffle Cake',
  },
  {
    id: 't2',
    name: 'Priya Sharma',
    location: 'Delhi',
    rating: 5,
    avatar: 'PS',
    text: 'The sourdough bread is exceptional. I\'ve tried many artisan bakeries across the city but Madhab\'s is in a different league. Crusty outside, perfectly chewy inside.',
    date: '1 month ago',
    product: 'Classic Sourdough Boule',
  },
  {
    id: 't3',
    name: 'Rohit Kapoor',
    location: 'Bangalore',
    rating: 5,
    avatar: 'RK',
    text: 'The butter croissants are legitimately the best I\'ve had outside of Paris. Delivery was fast and products arrived perfectly packaged. 10/10!',
    date: '3 weeks ago',
    product: 'Butter Croissants',
  },
  {
    id: 't4',
    name: 'Sunita Verma',
    location: 'Pune',
    rating: 5,
    avatar: 'SV',
    text: 'Madhab Bakery has been our go-to for all celebrations. The custom cake they made for our anniversary was beyond beautiful and tasted even better!',
    date: '1 week ago',
    product: 'Custom Celebration Cake',
  },
  {
    id: 't5',
    name: 'Vikram Nair',
    location: 'Hyderabad',
    rating: 5,
    avatar: 'VN',
    text: 'The fudgy espresso brownies are dangerously addictive. We\'ve made them a weekly order at the office. Everyone loves them!',
    date: '5 days ago',
    product: 'Fudgy Espresso Brownies',
  },
];

export const getFeaturedProducts = () => PRODUCTS.filter(p => p.tags.includes('featured')).slice(0, 8);
export const getBestSellers    = () => PRODUCTS.filter(p => p.isBestSeller).slice(0, 6);
export const getProductBySlug  = (slug) => PRODUCTS.find(p => p.slug === slug);
export const getByCategory     = (cat) => PRODUCTS.filter(p => p.category === cat);
export const getNewArrivals    = () => PRODUCTS.filter(p => p.isNew).slice(0, 6);
