export const ROUTES = {
  HOME:             '/',
  SHOP:             '/shop',
  PRODUCT_DETAIL:   '/product/:slug',
  CATEGORY:         '/category/:slug',
  CART:             '/cart',
  CHECKOUT:         '/checkout',
  ORDER_CONFIRM:    '/order-confirmation/:id',
  LOGIN:            '/login',
  REGISTER:         '/register',
  FORGOT_PASSWORD:  '/forgot-password',
  RESET_PASSWORD:   '/reset-password',
  ACCOUNT:          '/account',
  ACCOUNT_ORDERS:   '/account/orders',
  ACCOUNT_PROFILE:  '/account/profile',
  ACCOUNT_ADDRESSES:'/account/addresses',
  ACCOUNT_WISHLIST: '/account/wishlist',
  SEARCH:           '/search',
  ABOUT:            '/about',
  CONTACT:          '/contact',
  BLOG:             '/blog',
  BLOG_POST:        '/blog/:slug',
  NOT_FOUND:        '*',
};
